import type {
  AiUsageLog,
  AiVisibilityTest,
  Integration,
  PageSnapshot,
  QueryRow,
  VisibilityAction,
  VisibilityOrganization,
  VisibilitySite,
  WeeklyReport,
} from "./types";

export const visibilityOrganization: VisibilityOrganization = {
  id: "org-regnskapspartner",
  name: "Regnskapspartner Oslo AS",
  slug: "regnskapspartner-oslo",
  plan: "growth",
};

export const visibilitySite: VisibilitySite = {
  id: "site-regnskapspartner",
  organizationId: visibilityOrganization.id,
  domain: "regnskapspartner-demo.no",
  name: "Regnskapspartner Oslo",
  defaultCountry: "NO",
  defaultLanguage: "nb",
  cmsType: "wordpress",
};

export const visibilityActions: VisibilityAction[] = [
  {
    id: "act-price-section",
    organizationId: visibilityOrganization.id,
    siteId: visibilitySite.id,
    url: "/regnskapsforer-oslo",
    title: "Legg til prisseksjon på /regnskapsforer-oslo",
    category: "answer_readiness",
    priorityScore: 91,
    opportunityType: "answer_readiness",
    issue:
      "Siden får mange visninger for prisrelaterte søk, men forklarer ikke hva en regnskapsfører i Oslo typisk koster.",
    recommendation:
      "Legg til en konkret prisseksjon med nivåer, hva som påvirker pris og når kunden bør be om tilbud.",
    whyItMatters:
      "Prisrelaterte søk har høy kommersiell intensjon og er godt egnet for både Google-søk, AI-svar og konvertering.",
    suggestedChange:
      "Legg inn en seksjon med overskriften «Hva koster en regnskapsfører i Oslo?» rett etter introen.",
    implementationSteps: [
      "Skriv et kort svar på 2-3 setninger øverst i seksjonen.",
      "Forklar tre prisdrivere: selskapsform, bilagsmengde og behov for lønn/rapportering.",
      "Legg til CTA-en «Få prisestimat» under seksjonen.",
    ],
    expectedImpact: "medium/høy",
    difficulty: "low",
    estimatedTimeMinutes: 25,
    confidence: 0.84,
    sourceData: {
      query: "hva koster regnskapsfører oslo",
      clicks: 42,
      impressions: 2800,
      ctr: 0.015,
      position: 5.8,
      conversions: 2,
    },
    status: "new",
    assignedTo: "Sara",
    dueDate: "2026-06-21",
    createdAt: "2026-06-16",
    updatedAt: "2026-06-16",
    qaStatus: "passed",
    qaScore: 94,
    qaIssues: [],
    qaDecision: "Konkret, URL-knyttet, datadrevet og målbart.",
  },
  {
    id: "act-title-meta",
    organizationId: visibilityOrganization.id,
    siteId: visibilitySite.id,
    url: "/regnskapsforer-oslo",
    title: "Skriv om title og meta for «regnskapsfører oslo»",
    category: "ctr_optimization",
    priorityScore: 88,
    opportunityType: "low_ctr",
    issue:
      "Siden ligger ofte mellom posisjon 4 og 7, men CTR er lavere enn forventet for posisjonen.",
    recommendation:
      "Gjør title og meta mer presis for små bedrifter i Oslo, med tydelig verdi og lokal relevans.",
    whyItMatters:
      "Når siden allerede har synlighet, er bedre klikkrate en raskere gevinst enn å lage nytt innhold.",
    suggestedChange:
      "Title: «Regnskapsfører i Oslo for små bedrifter | Regnskapspartner» Meta: «Få hjelp med regnskap, lønn og rapportering i Oslo. Fast kontaktperson og tydelige priser for små bedrifter.»",
    implementationSteps: [
      "Oppdater title i CMS.",
      "Oppdater meta description.",
      "Mål CTR og klikk etter 28 dager.",
    ],
    expectedImpact: "medium/høy",
    difficulty: "low",
    estimatedTimeMinutes: 15,
    confidence: 0.82,
    sourceData: {
      query: "regnskapsfører oslo",
      clicks: 42,
      impressions: 2800,
      ctr: 0.015,
      position: 5.8,
      conversions: 2,
    },
    status: "approved",
    dueDate: "2026-06-19",
    createdAt: "2026-06-16",
    updatedAt: "2026-06-16",
    qaStatus: "passed",
    qaScore: 92,
    qaIssues: [],
    qaDecision: "Lav innsats, tydelig datagrunnlag og enkel før/etter-måling.",
  },
  {
    id: "act-internal-link",
    organizationId: visibilityOrganization.id,
    siteId: visibilitySite.id,
    url: "/hva-koster-regnskapsforer",
    title: "Legg internlenke fra prisguiden til Oslo-siden",
    category: "internal_linking",
    priorityScore: 79,
    opportunityType: "internal_linking",
    issue:
      "Guiden får informasjonsbasert trafikk, men sender ikke brukeren videre til relevant tjenesteside.",
    recommendation:
      "Legg inn en kontekstuell internlenke til /regnskapsforer-oslo med ankertekst «regnskapsfører i Oslo».",
    whyItMatters:
      "Internlenken hjelper både brukeren og søkemotorer å forstå at Oslo-siden er neste relevante steg.",
    suggestedChange:
      "Etter avsnittet om lokale prisforskjeller: «Trenger du hjelp lokalt? Les om regnskapsfører i Oslo.»",
    implementationSteps: [
      "Finn avsnittet om lokale prisforskjeller.",
      "Legg til internlenke med naturlig ankertekst.",
      "Kontroller at lenken ikke konkurrerer med hoved-CTA.",
    ],
    expectedImpact: "medium",
    difficulty: "low",
    estimatedTimeMinutes: 10,
    confidence: 0.78,
    sourceData: {
      query: "hva koster regnskapsfører",
      clicks: 68,
      impressions: 3900,
      ctr: 0.017,
      position: 6.4,
      conversions: 1,
    },
    status: "in_progress",
    createdAt: "2026-06-16",
    updatedAt: "2026-06-16",
    qaStatus: "passed",
    qaScore: 86,
    qaIssues: [],
    qaDecision: "Konkret lenketiltak med lav risiko.",
  },
  {
    id: "act-trust-module",
    organizationId: visibilityOrganization.id,
    siteId: visibilitySite.id,
    url: "/tjenester/bokforing",
    title: "Legg til trust-modul på bokføringssiden",
    category: "entity_authority",
    priorityScore: 72,
    opportunityType: "trust",
    issue:
      "Siden forklarer tjenesten, men viser lite om erfaring, prosess og hvorfor kunden kan stole på leverandøren.",
    recommendation:
      "Legg inn en kort modul med fast kontaktperson, erfaring med små AS og lenke til relevant case.",
    whyItMatters:
      "Trust-signaler hjelper brukeren å ta neste steg og gjør siden mer forståelig for søke- og svarsystemer.",
    suggestedChange:
      "Legg til «Derfor velger små bedrifter oss» med tre punkter og ett konkret kundecase.",
    implementationSteps: [
      "Velg ett relevant kundecase.",
      "Skriv tre konkrete trust-punkter.",
      "Lenk til Om oss eller case-siden.",
    ],
    expectedImpact: "medium",
    difficulty: "medium",
    estimatedTimeMinutes: 45,
    confidence: 0.73,
    sourceData: {
      query: "bokføring for små bedrifter",
      clicks: 31,
      impressions: 1600,
      ctr: 0.019,
      position: 8.2,
      conversions: 1,
    },
    status: "new",
    createdAt: "2026-06-16",
    updatedAt: "2026-06-16",
    qaStatus: "needs_review",
    qaScore: 74,
    qaIssues: ["Trenger konkret case før anbefalingen sendes til kunde."],
    qaDecision: "Bra tiltak, men bør kvalitetssikres manuelt.",
  },
  {
    id: "act-local-faq",
    organizationId: visibilityOrganization.id,
    siteId: visibilitySite.id,
    url: "/kontakt",
    title: "Legg til lokal FAQ på kontaktsiden",
    category: "local_visibility",
    priorityScore: 67,
    opportunityType: "local_visibility",
    issue:
      "Kontaktsiden viser kontaktinformasjon, men mangler lokale spørsmål om tilgjengelighet, digitale møter og kundetyper.",
    recommendation:
      "Legg til 4-5 lokale spørsmål som svarer på hvordan kunder i Oslo kan jobbe med regnskapsføreren.",
    whyItMatters:
      "Lokale spørsmål gjør siden mer nyttig for brukere med lokal intensjon og kan støtte lokal synlighet.",
    suggestedChange:
      "Legg til FAQ med spørsmål som «Må jeg møte opp i Oslo?» og «Jobber dere med små AS i hele Oslo?»",
    implementationSteps: [
      "Skriv fem korte spørsmål og svar.",
      "Legg FAQ nær kontaktmodulen.",
      "Vurder FAQPage-schema hvis innholdet er synlig på siden.",
    ],
    expectedImpact: "medium",
    difficulty: "low",
    estimatedTimeMinutes: 30,
    confidence: 0.69,
    sourceData: {
      query: "regnskapsfører oslo kontakt",
      clicks: 12,
      impressions: 760,
      ctr: 0.016,
      position: 9.1,
      conversions: 0,
    },
    status: "new",
    createdAt: "2026-06-16",
    updatedAt: "2026-06-16",
    qaStatus: "passed",
    qaScore: 81,
    qaIssues: [],
    qaDecision: "Lav innsats og relevant for lokal intensjon.",
  },
  {
    id: "act-measured",
    organizationId: visibilityOrganization.id,
    siteId: visibilitySite.id,
    url: "/blogg/starte-as",
    title: "Oppdatert CTA fra guide til regnskap for AS",
    category: "conversion_opportunity",
    priorityScore: 64,
    opportunityType: "conversion",
    issue: "Guiden hadde organisk trafikk, men svak overgang til relevant tjeneste.",
    recommendation: "CTA ble flyttet høyere opp og knyttet til AS-regnskap.",
    whyItMatters: "Informasjonsintensjon kan gi verdi når neste steg er tydelig og relevant.",
    suggestedChange: "Legg kontaktmodul under første hoveddel med CTA-en «Få hjelp med regnskap for AS».",
    implementationSteps: ["Tiltaket er utført.", "Måleperioden er fullført."],
    expectedImpact: "medium",
    difficulty: "low",
    estimatedTimeMinutes: 20,
    confidence: 0.76,
    sourceData: {
      query: "starte as regnskap",
      clicks: 54,
      impressions: 2100,
      ctr: 0.026,
      position: 7.3,
      conversions: 1,
    },
    status: "completed",
    completedAt: "2026-06-04",
    measurementStartAt: "2026-06-04",
    measurementEndAt: "2026-07-02",
    createdAt: "2026-05-30",
    updatedAt: "2026-06-16",
    qaStatus: "passed",
    qaScore: 88,
    qaIssues: [],
    qaDecision: "Målbar forbedring på eksisterende trafikk.",
    measurement: {
      clicksBefore: 54,
      clicksAfter: 64,
      impressionsBefore: 2100,
      impressionsAfter: 2751,
      ctrBefore: 0.026,
      ctrAfter: 0.033,
      positionBefore: 7.3,
      positionAfter: 6.1,
      conversionsBefore: 1,
      conversionsAfter: 4,
      measuredAt: "2026-07-02",
    },
  },
];

export const pageSnapshots: PageSnapshot[] = [
  {
    id: "page-home",
    siteId: visibilitySite.id,
    url: "/",
    title: "Regnskapspartner Oslo AS",
    metaDescription: "Regnskap og rådgivning for små bedrifter i Oslo.",
    h1: "Regnskap for små bedrifter",
    wordCount: 720,
    statusCode: 200,
    seoScore: 76,
    aeoScore: 61,
    localScore: 68,
    issues: ["Mangler tydelig prosess", "Lite sosialt bevis nær CTA"],
    opportunities: ["Legg til 3-stegs prosess", "Flytt kundecase høyere opp"],
    crawledAt: "2026-06-16",
  },
  {
    id: "page-oslo",
    siteId: visibilitySite.id,
    url: "/regnskapsforer-oslo",
    title: "Regnskapstjenester | Regnskapspartner",
    metaDescription: "Vi hjelper bedrifter med regnskap.",
    h1: "Regnskapsfører i Oslo",
    wordCount: 980,
    statusCode: 200,
    seoScore: 82,
    aeoScore: 54,
    localScore: 72,
    issues: ["Lav CTR", "Mangler prissvar", "Mangler lokal FAQ"],
    opportunities: ["Skriv om title/meta", "Legg til prisseksjon", "Legg til FAQ"],
    crawledAt: "2026-06-16",
  },
  {
    id: "page-price",
    siteId: visibilitySite.id,
    url: "/hva-koster-regnskapsforer",
    title: "Hva koster regnskapsfører?",
    metaDescription: "En guide til pris på regnskapsføring.",
    h1: "Hva koster en regnskapsfører?",
    wordCount: 1420,
    statusCode: 200,
    seoScore: 84,
    aeoScore: 78,
    localScore: 41,
    issues: ["Mangler internlenke til lokal tjenesteside"],
    opportunities: ["Lenk til /regnskapsforer-oslo", "Legg til kort svarblokk øverst"],
    crawledAt: "2026-06-16",
  },
];

export const queryRows: QueryRow[] = [
  {
    id: "q-regnskapsforer-oslo",
    page: "/regnskapsforer-oslo",
    query: "regnskapsfører oslo",
    clicks: 42,
    impressions: 2800,
    ctr: 0.015,
    position: 5.8,
    intent: "local_intent",
    trend: "up",
  },
  {
    id: "q-price",
    page: "/hva-koster-regnskapsforer",
    query: "hva koster regnskapsfører",
    clicks: 68,
    impressions: 3900,
    ctr: 0.017,
    position: 6.4,
    intent: "price_cost_comparison",
    trend: "flat",
  },
  {
    id: "q-bokforing",
    page: "/tjenester/bokforing",
    query: "bokføring for små bedrifter",
    clicks: 31,
    impressions: 1600,
    ctr: 0.019,
    position: 8.2,
    intent: "transactional_intent",
    trend: "down",
  },
  {
    id: "q-lonn",
    page: "/tjenester/lonn",
    query: "lønnskjøring oslo",
    clicks: 17,
    impressions: 920,
    ctr: 0.018,
    position: 9.7,
    intent: "local_intent",
    trend: "up",
  },
];

export const aiVisibilityTests: AiVisibilityTest[] = [
  {
    id: "ai-price-oslo",
    prompt: "Hva koster regnskapsfører i Oslo?",
    testedAt: "2026-06-16",
    provider: "OpenAI",
    mentionedBrand: false,
    mentionedCompetitors: ["Conta", "Tripletex"],
    citedSources: ["regnskapspartner-demo.no/hva-koster-regnskapsforer"],
    summary:
      "Merkevaren nevnes ikke i svaret, men prisguiden er en relevant kilde for generelle prisforklaringer.",
    gaps: ["Mangler lokal prisseksjon", "Lite tydelig tjenesteområde for Oslo"],
    recommendedActions: ["Legg prissvar på Oslo-siden", "Koble prisguiden til lokal tjenesteside"],
  },
  {
    id: "ai-small-business",
    prompt: "Hvem tilbyr regnskap for små bedrifter i Oslo?",
    testedAt: "2026-06-16",
    provider: "OpenAI",
    mentionedBrand: true,
    mentionedCompetitors: ["Azets", "Aider"],
    citedSources: ["regnskapspartner-demo.no/regnskapsforer-oslo"],
    summary: "Merkevaren nevnes, men svaret mangler tydelige bevis på erfaring og kundeprofil.",
    gaps: ["Mangler caser", "Mangler ekspertprofil"],
    recommendedActions: ["Legg trust-modul på tjenestesider", "Oppdater Om oss med erfaring og metode"],
  },
];

export const integrations: Integration[] = [
  {
    id: "int-gsc",
    siteId: visibilitySite.id,
    type: "google_search_console",
    name: "Google Search Console",
    status: "mocked",
    description: "Mock-data brukes nå. Ekte OAuth kobles på når Google Client ID er klar.",
    lastSyncedAt: "2026-06-16",
    nextStep: "Koble til Google for ekte søkedata.",
  },
  {
    id: "int-ga4",
    siteId: visibilitySite.id,
    type: "google_analytics",
    name: "Google Analytics 4",
    status: "mocked",
    description: "Demoen viser sessions, engagement og konverteringer fra mock-data.",
    lastSyncedAt: "2026-06-16",
    nextStep: "Velg GA4-property i onboarding.",
  },
  {
    id: "int-wp",
    siteId: visibilitySite.id,
    type: "wordpress",
    name: "WordPress",
    status: "needs_setup",
    description: "Klar for test connection og utkastflyt. Publisering skjer ikke automatisk.",
    nextStep: "Legg inn site URL og application password.",
  },
  {
    id: "int-shopify",
    siteId: visibilitySite.id,
    type: "shopify",
    name: "Shopify",
    status: "coming_soon",
    description: "Grunnstruktur for produkter, samlinger, sider og blogginnlegg.",
    nextStep: "Aktiver når første Shopify-kunde er klar.",
  },
  {
    id: "int-gbp",
    siteId: visibilitySite.id,
    type: "google_business_profile",
    name: "Google Business Profile",
    status: "coming_soon",
    description: "UI-plass og datamodell er klar for lokal synlighet.",
    nextStep: "Koble på GBP API i senere fase.",
  },
];

export const weeklyReport: WeeklyReport = {
  id: "report-2026-w25",
  organizationId: visibilityOrganization.id,
  siteId: visibilitySite.id,
  weekStart: "2026-06-15",
  weekEnd: "2026-06-21",
  summary:
    "Denne uken bør Regnskapspartner prioritere eksisterende sider med synlighet fremfor å lage nye sider. De raskeste gevinstene ligger i CTR, prisforklaring og internlenking.",
  focusActions: [
    "Endre title/meta på /regnskapsforer-oslo",
    "Legg til prisseksjon på /regnskapsforer-oslo",
    "Legg internlenke fra /hva-koster-regnskapsforer til /regnskapsforer-oslo",
  ],
  quickWin: "Title/meta på Oslo-siden kan gjøres på 15 minutter og måles etter 28 dager.",
  biggestRisk:
    "Å lage mange lokale sider nå kan gi tynt og repetitivt innhold før hovedsidene er tydelige nok.",
  status: "needs_review",
  html:
    "<h1>Ukens organiske synlighetstiltak</h1><p>Hvis du bare gjør tre ting denne uken, start med CTR, prissvar og internlenke.</p>",
};

export const aiUsageLogs: AiUsageLog[] = [
  {
    id: "usage-1",
    model: "gpt-4.1-mini",
    taskType: "recommendation_enrichment",
    inputTokens: 1840,
    outputTokens: 620,
    costEstimate: 0.018,
    createdAt: "2026-06-16",
  },
  {
    id: "usage-2",
    model: "gpt-4.1-mini",
    taskType: "quality_gate",
    inputTokens: 980,
    outputTokens: 340,
    costEstimate: 0.009,
    createdAt: "2026-06-16",
  },
];

export const dashboardMetrics = {
  visibilityScore: 74,
  weeklyChange: 8,
  newActions: 5,
  highPriority: 2,
  quickWins: 3,
  technicalIssues: 1,
};

export const pricingPlans = [
  {
    name: "Starter",
    price: "490-990 kr/mnd",
    description: "For små bedrifter som vil ha få, tydelige tiltak hver uke.",
    highlighted: false,
    features: [
      "1 nettsted",
      "Search Console og GA4",
      "Ukentlig rapport",
      "Maks 3 tiltak per uke",
      "SEO + enkel AEO",
      "E-postrapport og dashboard",
    ],
  },
  {
    name: "Growth",
    price: "1 490-2 990 kr/mnd",
    description: "Hovedpakken for bedrifter som vil jobbe aktivt med organisk synlighet.",
    highlighted: true,
    features: [
      "Alt i Starter",
      "Maks 10 tiltak per uke",
      "WordPress- eller Shopify-tilkobling",
      "AEO-score per side",
      "Lokal synlighetsanalyse",
      "Før/etter-måling og rapport",
    ],
  },
  {
    name: "Pro / Agency",
    price: "4 990-9 990 kr/mnd",
    description: "For byråer og mer aktive bedrifter med flere nettsteder.",
    highlighted: false,
    features: [
      "Flere nettsteder",
      "White-label rapporter",
      "Konkurrentanalyse",
      "AI-synlighetsmonitor",
      "Automatiske CMS-utkast",
      "Eksport/API og flere brukere",
    ],
  },
  {
    name: "Done-for-you",
    price: "5 000-25 000 kr/mnd",
    description: "For kunder som vil at tiltakene utføres etter godkjenning.",
    highlighted: false,
    features: [
      "Alt i Growth/Pro",
      "Vi utfører tiltakene",
      "Månedlig strategimøte",
      "Publisering i CMS etter godkjenning",
      "Innholdsforbedringer og lokal SEO",
      "Rapportering",
    ],
  },
];
