import type {
  AiUsageLog,
  AiVisibilityTest,
  CompetitorObservation,
  DescriptionAudit,
  ExternalAuthorityRecommendation,
  Integration,
  KeywordAlert,
  KeywordCluster,
  MonitoredKeyword,
  PageSnapshot,
  PaidAdsAlert,
  PaidAdsCampaign,
  PaidLandingPageObservation,
  QueryRow,
  VisibilityAction,
  VisibilityOrganization,
  VisibilitySite,
  WeeklyReport,
} from "./types";

export const visibilityOrganization: VisibilityOrganization = {
  id: "org-regnskapspartner",
  name: "Regnskapspartner Oslo AS",
  slug: "regnskapspartner-oslo",
  plan: "growth",
};

export const visibilitySite: VisibilitySite = {
  id: "site-regnskapspartner",
  organizationId: visibilityOrganization.id,
  domain: "regnskapspartner-demo.no",
  name: "Regnskapspartner Oslo",
  defaultCountry: "NO",
  defaultLanguage: "nb",
  cmsType: "wordpress",
};

export const visibilityActions: VisibilityAction[] = [
  {
    id: "act-price-section",
    organizationId: visibilityOrganization.id,
    siteId: visibilitySite.id,
    url: "/regnskapsforer-oslo",
    title: "Legg til prisseksjon på /regnskapsforer-oslo",
    category: "answer_readiness",
    priorityScore: 91,
    opportunityType: "answer_readiness",
    issue:
      "Siden får mange visninger for prisrelaterte søk, men forklarer ikke hva en regnskapsfører i Oslo typisk koster.",
    recommendation:
      "Legg til en konkret prisseksjon med nivåer, hva som påvirker pris og når kunden bør be om tilbud.",
    whyItMatters:
      "Prisrelaterte søk har høy kommersiell intensjon og er godt egnet for både Google-søk, AI-svar og konvertering.",
    suggestedChange:
      "Legg inn en seksjon med overskriften «Hva koster en regnskapsfører i Oslo?» rett etter introen.",
    implementationSteps: [
      "Skriv et kort svar på 2-3 setninger øverst i seksjonen.",
      "Forklar tre prisdrivere: selskapsform, bilagsmengde og behov for lønn/rapportering.",
      "Legg til CTA-en «Få prisestimat» under seksjonen.",
    ],
    expectedImpact: "medium/høy",
    difficulty: "low",
    estimatedTimeMinutes: 25,
    confidence: 0.84,
    sourceData: {
      query: "hva koster regnskapsfører oslo",
      clicks: 42,
      impressions: 2800,
      ctr: 0.015,
      position: 5.8,
      conversions: 2,
    },
    status: "new",
    assignedTo: "Sara",
    dueDate: "2026-06-21",
    createdAt: "2026-06-16",
    updatedAt: "2026-06-16",
    qaStatus: "passed",
    qaScore: 94,
    qaIssues: [],
    qaDecision: "Konkret, URL-knyttet, datadrevet og målbart.",
  },
  {
    id: "act-title-meta",
    organizationId: visibilityOrganization.id,
    siteId: visibilitySite.id,
    url: "/regnskapsforer-oslo",
    title: "Skriv om title og meta for «regnskapsfører oslo»",
    category: "ctr_optimization",
    priorityScore: 88,
    opportunityType: "low_ctr",
    issue:
      "Siden ligger ofte mellom posisjon 4 og 7, men CTR er lavere enn forventet for posisjonen.",
    recommendation:
      "Gjør title og meta mer presis for små bedrifter i Oslo, med tydelig verdi og lokal relevans.",
    whyItMatters:
      "Når siden allerede har synlighet, er bedre klikkrate en raskere gevinst enn å lage nytt innhold.",
    suggestedChange:
      "Title: «Regnskapsfører i Oslo for små bedrifter | Regnskapspartner» Meta: «Få hjelp med regnskap, lønn og rapportering i Oslo. Fast kontaktperson og tydelige priser for små bedrifter.»",
    implementationSteps: [
      "Oppdater title i CMS.",
      "Oppdater meta description.",
      "Mål CTR og klikk etter 28 dager.",
    ],
    expectedImpact: "medium/høy",
    difficulty: "low",
    estimatedTimeMinutes: 15,
    confidence: 0.82,
    sourceData: {
      query: "regnskapsfører oslo",
      clicks: 42,
      impressions: 2800,
      ctr: 0.015,
      position: 5.8,
      conversions: 2,
    },
    status: "approved",
    dueDate: "2026-06-19",
    createdAt: "2026-06-16",
    updatedAt: "2026-06-16",
    qaStatus: "passed",
    qaScore: 92,
    qaIssues: [],
    qaDecision: "Lav innsats, tydelig datagrunnlag og enkel før/etter-måling.",
  },
  {
    id: "act-internal-link",
    organizationId: visibilityOrganization.id,
    siteId: visibilitySite.id,
    url: "/hva-koster-regnskapsforer",
    title: "Legg internlenke fra prisguiden til Oslo-siden",
    category: "internal_linking",
    priorityScore: 79,
    opportunityType: "internal_linking",
    issue:
      "Guiden får informasjonsbasert trafikk, men sender ikke brukeren videre til relevant tjenesteside.",
    recommendation:
      "Legg inn en kontekstuell internlenke til /regnskapsforer-oslo med ankertekst «regnskapsfører i Oslo».",
    whyItMatters:
      "Internlenken hjelper både brukeren og søkemotorer å forstå at Oslo-siden er neste relevante steg.",
    suggestedChange:
      "Etter avsnittet om lokale prisforskjeller: «Trenger du hjelp lokalt? Les om regnskapsfører i Oslo.»",
    implementationSteps: [
      "Finn avsnittet om lokale prisforskjeller.",
      "Legg til internlenke med naturlig ankertekst.",
      "Kontroller at lenken ikke konkurrerer med hoved-CTA.",
    ],
    expectedImpact: "medium",
    difficulty: "low",
    estimatedTimeMinutes: 10,
    confidence: 0.78,
    sourceData: {
      query: "hva koster regnskapsfører",
      clicks: 68,
      impressions: 3900,
      ctr: 0.017,
      position: 6.4,
      conversions: 1,
    },
    status: "in_progress",
    createdAt: "2026-06-16",
    updatedAt: "2026-06-16",
    qaStatus: "passed",
    qaScore: 86,
    qaIssues: [],
    qaDecision: "Konkret lenketiltak med lav risiko.",
  },
  {
    id: "act-trust-module",
    organizationId: visibilityOrganization.id,
    siteId: visibilitySite.id,
    url: "/tjenester/bokforing",
    title: "Legg til trust-modul på bokføringssiden",
    category: "entity_authority",
    priorityScore: 72,
    opportunityType: "trust",
    issue:
      "Siden forklarer tjenesten, men viser lite om erfaring, prosess og hvorfor kunden kan stole på leverandøren.",
    recommendation:
      "Legg inn en kort modul med fast kontaktperson, erfaring med små AS og lenke til relevant case.",
    whyItMatters:
      "Trust-signaler hjelper brukeren å ta neste steg og gjør siden mer forståelig for søke- og svarsystemer.",
    suggestedChange:
      "Legg til «Derfor velger små bedrifter oss» med tre punkter og ett konkret kundecase.",
    implementationSteps: [
      "Velg ett relevant kundecase.",
      "Skriv tre konkrete trust-punkter.",
      "Lenk til Om oss eller case-siden.",
    ],
    expectedImpact: "medium",
    difficulty: "medium",
    estimatedTimeMinutes: 45,
    confidence: 0.73,
    sourceData: {
      query: "bokføring for små bedrifter",
      clicks: 31,
      impressions: 1600,
      ctr: 0.019,
      position: 8.2,
      conversions: 1,
    },
    status: "new",
    createdAt: "2026-06-16",
    updatedAt: "2026-06-16",
    qaStatus: "needs_review",
    qaScore: 74,
    qaIssues: ["Trenger konkret case før anbefalingen sendes til kunde."],
    qaDecision: "Bra tiltak, men bør kvalitetssikres manuelt.",
  },
  {
    id: "act-external-mentions",
    organizationId: visibilityOrganization.id,
    siteId: visibilitySite.id,
    url: "/om-oss",
    title: "Bygg eksterne autoritetssignaler for Regnskapspartner",
    category: "reputation_signal",
    priorityScore: 70,
    opportunityType: "external_authority",
    issue:
      "Konkurrenter som Aider og Azets har sterkere eksterne merkevaresignaler. Regnskapspartner er lite synlig på relevante bransje- og lokalsider.",
    recommendation:
      "Lag en kort outreach-liste med relevante eksterne steder der bedriften naturlig bør nevnes, uten kjøpte lenker eller spam.",
    whyItMatters:
      "Eksterne omtaler fra relevante og troverdige sider kan styrke tillit, merkevareforståelse og sannsynligheten for å bli vurdert i søk og AI-svar.",
    suggestedChange:
      "Kontakt 3-5 relevante aktører: lokal næringsforening, bransjeoversikter, samarbeidspartnere og kundecaser der Regnskapspartner kan nevnes med lenke.",
    implementationSteps: [
      "Lag liste over 10 relevante eksterne kilder med reell relasjon eller faglig relevans.",
      "Prioriter kilder som kan omtale bedriften naturlig: samarbeidspartnere, lokale næringsmiljøer og bransjeprofiler.",
      "Foreslå én konkret ressurs de kan lenke til, for eksempel Om oss, case eller prisside.",
      "Mål nye henvisninger, brand mentions og referral-trafikk etter 60 dager.",
    ],
    expectedImpact: "medium",
    difficulty: "medium",
    estimatedTimeMinutes: 90,
    confidence: 0.67,
    sourceData: {
      query: "regnskapsfører oslo",
      clicks: 42,
      impressions: 2800,
      ctr: 0.015,
      position: 5.8,
      conversions: 2,
    },
    status: "new",
    createdAt: "2026-06-16",
    updatedAt: "2026-06-16",
    qaStatus: "passed",
    qaScore: 84,
    qaIssues: [],
    qaDecision: "Relevant ekstern autoritet, tydelig måling og lav spamrisiko når det gjøres relasjonsbasert.",
  },
  {
    id: "act-product-description",
    organizationId: visibilityOrganization.id,
    siteId: visibilitySite.id,
    url: "/produkter/regnskapspakke-start",
    title: "Skriv bedre produktbeskrivelse for Regnskapspakke Start",
    category: "content_gap",
    priorityScore: 83,
    opportunityType: "weak_description",
    issue:
      "Produktsiden har kort og generisk beskrivelse. Den forklarer ikke hvem pakken passer for, hva som er inkludert, begrensninger eller neste steg.",
    recommendation:
      "Utvid produktbeskrivelsen med målgruppe, inkluderte leveranser, typiske spørsmål, dokumentasjon og tydelig CTA.",
    whyItMatters:
      "Svake produktbeskrivelser gjør det vanskeligere å rangere, bli brukt i AI-svar og konvertere organisk trafikk.",
    suggestedChange:
      "Legg til seksjonene «Passer for», «Dette er inkludert», «Før du bestiller» og en kort FAQ.",
    implementationSteps: [
      "Skriv 120-180 ord unik produkttekst som forklarer hvem pakken passer for.",
      "Legg til punktliste med inkluderte leveranser og hva som ikke er inkludert.",
      "Legg inn 3 vanlige spørsmål om pris, oppstart og dokumentasjon.",
      "Avslutt med CTA-en «Be om vurdering av regnskapsbehov».",
    ],
    expectedImpact: "medium/høy",
    difficulty: "medium",
    estimatedTimeMinutes: 40,
    confidence: 0.79,
    sourceData: {
      query: "regnskapspakke små bedrifter",
      clicks: 9,
      impressions: 680,
      ctr: 0.013,
      position: 10.4,
      conversions: 0,
    },
    status: "new",
    createdAt: "2026-06-16",
    updatedAt: "2026-06-16",
    qaStatus: "passed",
    qaScore: 89,
    qaIssues: [],
    qaDecision: "Konkret forbedring av svak produkttekst med klar URL, innholdskrav og måling.",
  },
  {
    id: "act-paid-landing-page",
    organizationId: visibilityOrganization.id,
    siteId: visibilitySite.id,
    url: "/regnskapsforer-oslo",
    title: "Stopp annonsetap på Oslo-landingssiden",
    category: "paid_ads",
    priorityScore: 88,
    opportunityType: "paid_ads_waste",
    issue:
      "Google Ads-kampanjen bruker mest budsjett på Oslo-siden, men CPA har økt og siden mangler prissvar som matcher annonseteksten.",
    recommendation:
      "Stram inn søkeord, legg til negative søk og oppdater landingssiden med prissvar før budsjettet økes igjen.",
    whyItMatters:
      "Betalt trafikk kan bli dyr når annonsens løfte og landingssiden ikke svarer på samme behov. Dette påvirker både CPA og organisk konvertering.",
    suggestedChange:
      "Pause dyreste annonsegruppe midlertidig, legg inn negative søk og legg prisseksjon øverst på /regnskapsforer-oslo.",
    implementationSteps: [
      "Gå gjennom søketerms og legg til irrelevante søk som negative keywords.",
      "Senk budsjettet på annonsegruppen til landingssiden er oppdatert.",
      "Legg prissvar og tydelig CTA i første skjermbilde.",
      "Mål CPA, konverteringsrate og organisk/paid samlet effekt etter 14 dager.",
    ],
    expectedImpact: "høy",
    difficulty: "medium",
    estimatedTimeMinutes: 60,
    confidence: 0.82,
    sourceData: {
      query: "regnskapsfører oslo pris",
      clicks: 184,
      impressions: 5400,
      ctr: 0.034,
      position: 1.2,
      conversions: 4,
    },
    status: "new",
    createdAt: "2026-06-16",
    updatedAt: "2026-06-16",
    qaStatus: "passed",
    qaScore: 90,
    qaIssues: [],
    qaDecision: "Tydelig kobling mellom annonsekostnad, landingsside og målbar CPA-effekt.",
  },
  {
    id: "act-local-faq",
    organizationId: visibilityOrganization.id,
    siteId: visibilitySite.id,
    url: "/kontakt",
    title: "Legg til lokal FAQ på kontaktsiden",
    category: "local_visibility",
    priorityScore: 67,
    opportunityType: "local_visibility",
    issue:
      "Kontaktsiden viser kontaktinformasjon, men mangler lokale spørsmål om tilgjengelighet, digitale møter og kundetyper.",
    recommendation:
      "Legg til 4-5 lokale spørsmål som svarer på hvordan kunder i Oslo kan jobbe med regnskapsføreren.",
    whyItMatters:
      "Lokale spørsmål gjør siden mer nyttig for brukere med lokal intensjon og kan støtte lokal synlighet.",
    suggestedChange:
      "Legg til FAQ med spørsmål som «Må jeg møte opp i Oslo?» og «Jobber dere med små AS i hele Oslo?»",
    implementationSteps: [
      "Skriv fem korte spørsmål og svar.",
      "Legg FAQ nær kontaktmodulen.",
      "Vurder FAQPage-schema hvis innholdet er synlig på siden.",
    ],
    expectedImpact: "medium",
    difficulty: "low",
    estimatedTimeMinutes: 30,
    confidence: 0.69,
    sourceData: {
      query: "regnskapsfører oslo kontakt",
      clicks: 12,
      impressions: 760,
      ctr: 0.016,
      position: 9.1,
      conversions: 0,
    },
    status: "new",
    createdAt: "2026-06-16",
    updatedAt: "2026-06-16",
    qaStatus: "passed",
    qaScore: 81,
    qaIssues: [],
    qaDecision: "Lav innsats og relevant for lokal intensjon.",
  },
  {
    id: "act-measured",
    organizationId: visibilityOrganization.id,
    siteId: visibilitySite.id,
    url: "/blogg/starte-as",
    title: "Oppdatert CTA fra guide til regnskap for AS",
    category: "conversion_opportunity",
    priorityScore: 64,
    opportunityType: "conversion",
    issue: "Guiden hadde organisk trafikk, men svak overgang til relevant tjeneste.",
    recommendation: "CTA ble flyttet høyere opp og knyttet til AS-regnskap.",
    whyItMatters: "Informasjonsintensjon kan gi verdi når neste steg er tydelig og relevant.",
    suggestedChange: "Legg kontaktmodul under første hoveddel med CTA-en «Få hjelp med regnskap for AS».",
    implementationSteps: ["Tiltaket er utført.", "Måleperioden er fullført."],
    expectedImpact: "medium",
    difficulty: "low",
    estimatedTimeMinutes: 20,
    confidence: 0.76,
    sourceData: {
      query: "starte as regnskap",
      clicks: 54,
      impressions: 2100,
      ctr: 0.026,
      position: 7.3,
      conversions: 1,
    },
    status: "completed",
    completedAt: "2026-06-04",
    measurementStartAt: "2026-06-04",
    measurementEndAt: "2026-07-02",
    createdAt: "2026-05-30",
    updatedAt: "2026-06-16",
    qaStatus: "passed",
    qaScore: 88,
    qaIssues: [],
    qaDecision: "Målbar forbedring på eksisterende trafikk.",
    measurement: {
      clicksBefore: 54,
      clicksAfter: 64,
      impressionsBefore: 2100,
      impressionsAfter: 2751,
      ctrBefore: 0.026,
      ctrAfter: 0.033,
      positionBefore: 7.3,
      positionAfter: 6.1,
      conversionsBefore: 1,
      conversionsAfter: 4,
      measuredAt: "2026-07-02",
    },
  },
];

export const pageSnapshots: PageSnapshot[] = [
  {
    id: "page-home",
    siteId: visibilitySite.id,
    url: "/",
    title: "Regnskapspartner Oslo AS",
    metaDescription: "Regnskap og rådgivning for små bedrifter i Oslo.",
    h1: "Regnskap for små bedrifter",
    pageType: "home",
    descriptionScore: 68,
    wordCount: 720,
    statusCode: 200,
    seoScore: 76,
    aeoScore: 61,
    localScore: 68,
    issues: ["Mangler tydelig prosess", "Lite sosialt bevis nær CTA", "Lite dokumentasjon fra troverdige kilder"],
    opportunities: [
      "Legg til 3-stegs prosess",
      "Flytt kundecase høyere opp",
      "Lenk til relevante offentlige kilder der det forklarer regler eller frister",
    ],
    crawledAt: "2026-06-16",
  },
  {
    id: "page-oslo",
    siteId: visibilitySite.id,
    url: "/regnskapsforer-oslo",
    title: "Regnskapstjenester | Regnskapspartner",
    metaDescription: "Vi hjelper bedrifter med regnskap.",
    h1: "Regnskapsfører i Oslo",
    pageType: "service",
    descriptionScore: 58,
    wordCount: 980,
    statusCode: 200,
    seoScore: 82,
    aeoScore: 54,
    localScore: 72,
    issues: ["Lav CTR", "Mangler prissvar", "Mangler lokal FAQ"],
    opportunities: ["Skriv om title/meta", "Legg til prisseksjon", "Legg til FAQ"],
    crawledAt: "2026-06-16",
  },
  {
    id: "page-price",
    siteId: visibilitySite.id,
    url: "/hva-koster-regnskapsforer",
    title: "Hva koster regnskapsfører?",
    metaDescription: "En guide til pris på regnskapsføring.",
    h1: "Hva koster en regnskapsfører?",
    pageType: "article",
    descriptionScore: 74,
    wordCount: 1420,
    statusCode: 200,
    seoScore: 84,
    aeoScore: 78,
    localScore: 41,
    issues: ["Mangler internlenke til lokal tjenesteside", "Mangler eksterne kilder for regel- og prisforklaring"],
    opportunities: [
      "Lenk til /regnskapsforer-oslo",
      "Legg til kort svarblokk øverst",
      "Lenk til Altinn eller Skatteetaten der guiden omtaler lovpålagte frister",
    ],
    crawledAt: "2026-06-16",
  },
  {
    id: "page-product-start",
    siteId: visibilitySite.id,
    url: "/produkter/regnskapspakke-start",
    title: "Regnskapspakke Start",
    metaDescription: "En enkel regnskapspakke for små bedrifter.",
    h1: "Regnskapspakke Start",
    pageType: "product",
    descriptionScore: 34,
    wordCount: 118,
    statusCode: 200,
    seoScore: 49,
    aeoScore: 38,
    localScore: 32,
    issues: [
      "Svak produktbeskrivelse",
      "Mangler hvem produktet passer for",
      "Mangler hva som er inkludert",
      "Mangler FAQ og neste steg",
    ],
    opportunities: [
      "Utvid produktbeskrivelsen med målgruppe og inkluderte leveranser",
      "Legg til FAQ om oppstart, pris og dokumentasjon",
      "Legg tydelig CTA under produktbeskrivelsen",
    ],
    crawledAt: "2026-06-16",
  },
  {
    id: "page-collection-packages",
    siteId: visibilitySite.id,
    url: "/produkter",
    title: "Regnskapspakker",
    metaDescription: "Se våre regnskapspakker.",
    h1: "Regnskapspakker",
    pageType: "collection",
    descriptionScore: 41,
    wordCount: 190,
    statusCode: 200,
    seoScore: 55,
    aeoScore: 44,
    localScore: 35,
    issues: ["Svak kategoribeskrivelse", "Mangler sammenligning", "Mangler kjøpshjelp"],
    opportunities: [
      "Forklar forskjellen på pakkene",
      "Legg til sammenligningstabell",
      "Legg til «hvilken pakke passer for meg?»",
    ],
    crawledAt: "2026-06-16",
  },
];

export const descriptionAudits: DescriptionAudit[] = [
  {
    id: "desc-product-start",
    siteId: visibilitySite.id,
    url: "/produkter/regnskapspakke-start",
    pageType: "product",
    title: "Regnskapspakke Start",
    currentDescription: "En enkel regnskapspakke for små bedrifter.",
    descriptionScore: 34,
    wordCount: 118,
    issue:
      "Beskrivelsen er for kort og generisk. Den svarer ikke på hvem pakken passer for, hva som er inkludert eller hva kunden må ha klart.",
    missingElements: [
      "Målgruppe",
      "Inkluderte leveranser",
      "Begrensninger",
      "Pris-/oppstartsforklaring",
      "FAQ",
      "Tydelig CTA",
    ],
    recommendedDescriptionBrief:
      "Skriv en konkret produktbeskrivelse for små AS og ENK som trenger fast regnskapshjelp. Forklar inkludert arbeid, typisk oppstart og når kunden bør velge en større pakke.",
    suggestedSections: ["Passer for", "Dette er inkludert", "Før du bestiller", "Vanlige spørsmål"],
    priority: 83,
    expectedImpact: "medium/høy",
    estimatedTimeMinutes: 40,
    source: "shopify",
  },
  {
    id: "desc-collection-packages",
    siteId: visibilitySite.id,
    url: "/produkter",
    pageType: "collection",
    title: "Regnskapspakker",
    currentDescription: "Se våre regnskapspakker.",
    descriptionScore: 41,
    wordCount: 190,
    issue:
      "Kategorisiden hjelper ikke brukeren å velge mellom pakkene og gir lite unik tekst for søk og AI-svar.",
    missingElements: [
      "Sammenligning mellom pakker",
      "Kjøpshjelp",
      "Hvem pakkene passer for",
      "Interne lenker til relevante guider",
    ],
    recommendedDescriptionBrief:
      "Forklar forskjellen på pakkene, hvem som bør velge hva, og lenk til prisguide eller kontakt for vurdering.",
    suggestedSections: ["Hvilken pakke passer for deg?", "Sammenligning", "Dette bør du vite før du velger"],
    priority: 74,
    expectedImpact: "medium",
    estimatedTimeMinutes: 50,
    source: "shopify",
  },
  {
    id: "desc-service-oslo",
    siteId: visibilitySite.id,
    url: "/regnskapsforer-oslo",
    pageType: "service",
    title: "Regnskapsfører i Oslo",
    currentDescription: "Vi hjelper bedrifter med regnskap.",
    descriptionScore: 58,
    wordCount: 980,
    issue:
      "Siden har nok tekst, men introduksjon og meta description er for generiske og mangler lokal differensiering.",
    missingElements: ["Tydelig lokal verdi", "Prisforklaring", "Hvem siden passer for"],
    recommendedDescriptionBrief:
      "Gjør starten mer spesifikk for små bedrifter i Oslo, og forklar hva kunden får hjelp med før CTA.",
    suggestedSections: ["Kort svar øverst", "Pris og oppstart", "For små bedrifter i Oslo"],
    priority: 68,
    expectedImpact: "medium",
    estimatedTimeMinutes: 25,
    source: "crawl",
  },
];

export const queryRows: QueryRow[] = [
  {
    id: "q-regnskapsforer-oslo",
    page: "/regnskapsforer-oslo",
    query: "regnskapsfører oslo",
    clicks: 42,
    impressions: 2800,
    ctr: 0.015,
    position: 5.8,
    intent: "local_intent",
    trend: "up",
  },
  {
    id: "q-price",
    page: "/hva-koster-regnskapsforer",
    query: "hva koster regnskapsfører",
    clicks: 68,
    impressions: 3900,
    ctr: 0.017,
    position: 6.4,
    intent: "price_cost_comparison",
    trend: "flat",
  },
  {
    id: "q-bokforing",
    page: "/tjenester/bokforing",
    query: "bokføring for små bedrifter",
    clicks: 31,
    impressions: 1600,
    ctr: 0.019,
    position: 8.2,
    intent: "transactional_intent",
    trend: "down",
  },
  {
    id: "q-lonn",
    page: "/tjenester/lonn",
    query: "lønnskjøring oslo",
    clicks: 17,
    impressions: 920,
    ctr: 0.018,
    position: 9.7,
    intent: "local_intent",
    trend: "up",
  },
];

export const monitoredKeywords: MonitoredKeyword[] = [
  {
    id: "kw-regnskapsforer-oslo",
    siteId: visibilitySite.id,
    keyword: "regnskapsfører oslo",
    targetUrl: "/regnskapsforer-oslo",
    currentUrl: "/regnskapsforer-oslo",
    intent: "local_intent",
    priority: 94,
    position: 5.8,
    previousPosition: 7.1,
    bestPosition: 4.9,
    clicks: 42,
    impressions: 2800,
    ctr: 0.015,
    conversionValue: "høy",
    serpFeatures: ["local_pack", "people_also_ask", "reviews"],
    competitors: ["aider.no", "azets.no", "regnskapnorge.no"],
    status: "action_needed",
    nextAction: "Skriv om title/meta og legg til lokal prisseksjon før ny lokal side lages.",
    updatedAt: "2026-06-16",
  },
  {
    id: "kw-price",
    siteId: visibilitySite.id,
    keyword: "hva koster regnskapsfører",
    targetUrl: "/hva-koster-regnskapsforer",
    currentUrl: "/hva-koster-regnskapsforer",
    intent: "price_cost_comparison",
    priority: 89,
    position: 6.4,
    previousPosition: 6.2,
    bestPosition: 5.7,
    clicks: 68,
    impressions: 3900,
    ctr: 0.017,
    conversionValue: "høy",
    serpFeatures: ["featured_snippet", "people_also_ask", "ai_overview"],
    competitors: ["tripletex.no", "conta.no", "fiken.no"],
    status: "action_needed",
    nextAction: "Legg kort svarblokk øverst og lenk videre til Oslo-siden.",
    updatedAt: "2026-06-16",
  },
  {
    id: "kw-bokforing",
    siteId: visibilitySite.id,
    keyword: "bokføring for små bedrifter",
    targetUrl: "/tjenester/bokforing",
    currentUrl: "/tjenester/bokforing",
    intent: "transactional_intent",
    priority: 76,
    position: 8.2,
    previousPosition: 6.9,
    bestPosition: 6.4,
    clicks: 31,
    impressions: 1600,
    ctr: 0.019,
    conversionValue: "medium",
    serpFeatures: ["people_also_ask"],
    competitors: ["aider.no", "azets.no"],
    status: "action_needed",
    nextAction: "Legg til trust-modul og case før mer nytt innhold produseres.",
    updatedAt: "2026-06-16",
  },
  {
    id: "kw-lonn",
    siteId: visibilitySite.id,
    keyword: "lønnskjøring oslo",
    targetUrl: "/tjenester/lonn",
    currentUrl: "/kontakt",
    intent: "local_intent",
    priority: 71,
    position: 9.7,
    previousPosition: 11.4,
    bestPosition: 9.7,
    clicks: 17,
    impressions: 920,
    ctr: 0.018,
    conversionValue: "medium",
    serpFeatures: ["local_pack"],
    competitors: ["azets.no", "aider.no"],
    status: "action_needed",
    nextAction: "Rett internlenking og innhold slik at /tjenester/lonn er tydelig vinnerside.",
    updatedAt: "2026-06-16",
  },
  {
    id: "kw-start-as",
    siteId: visibilitySite.id,
    keyword: "starte as regnskap",
    targetUrl: "/blogg/starte-as",
    currentUrl: "/blogg/starte-as",
    intent: "problem_friction_intent",
    priority: 63,
    position: 6.1,
    previousPosition: 7.3,
    bestPosition: 6.1,
    clicks: 64,
    impressions: 2751,
    ctr: 0.033,
    conversionValue: "medium",
    serpFeatures: ["people_also_ask", "featured_snippet"],
    competitors: ["altinn.no", "fiken.no", "tripletex.no"],
    status: "measuring",
    nextAction: "Fortsett måleperioden etter CTA-endringen før nye tiltak settes.",
    updatedAt: "2026-06-16",
  },
];

export const keywordAlerts: KeywordAlert[] = [
  {
    id: "alert-near-top-3",
    siteId: visibilitySite.id,
    keywordId: "kw-regnskapsforer-oslo",
    type: "near_top_3",
    severity: "high",
    title: "Nær topp 3 på lokalt hovedsøk",
    description: "«regnskapsfører oslo» ligger på 5,8 og har høy kommersiell verdi.",
    recommendedAction: "Prioriter CTR, prisforklaring og lokal FAQ før nye sider.",
    createdAt: "2026-06-16",
  },
  {
    id: "alert-low-ctr-price",
    siteId: visibilitySite.id,
    keywordId: "kw-price",
    type: "low_ctr",
    severity: "high",
    title: "Høy synlighet, lav CTR på prissøk",
    description: "3 900 visninger og 1,7 % CTR tyder på at søkeresultatet kan være for svakt.",
    recommendedAction: "Legg kort svarblokk og vurder ny title/meta med prisintensjon.",
    createdAt: "2026-06-16",
  },
  {
    id: "alert-drop-bokforing",
    siteId: visibilitySite.id,
    keywordId: "kw-bokforing",
    type: "position_drop",
    severity: "medium",
    title: "Faller på bokføringssøket",
    description: "Posisjon gikk fra 6,9 til 8,2 siden forrige måling.",
    recommendedAction: "Se om konkurrenter har bedre trust-signaler, prosessforklaring eller FAQ.",
    createdAt: "2026-06-16",
  },
  {
    id: "alert-wrong-url-lonn",
    siteId: visibilitySite.id,
    keywordId: "kw-lonn",
    type: "wrong_url",
    severity: "medium",
    title: "Feil URL rangerer for lønnskjøring",
    description: "Kontaktsiden vises oftere enn tjenestesiden for «lønnskjøring oslo».",
    recommendedAction: "Styr interne lenker og innholdsdekning mot /tjenester/lonn.",
    createdAt: "2026-06-16",
  },
];

export const keywordClusters: KeywordCluster[] = [
  {
    id: "cluster-local",
    siteId: visibilitySite.id,
    name: "Lokale kjøpssøk",
    intent: "local_intent",
    commercialValue: 92,
    coverageScore: 68,
    keywordIds: ["kw-regnskapsforer-oslo", "kw-lonn"],
    winningPageType: "Lokal tjenesteside med pris, FAQ, kontakt og trust-signaler",
    gap: "Søkerne ser lokal relevans, men pris og lokal FAQ er ikke tydelige nok.",
    recommendedNextStep: "Forbedre Oslo-siden før det lages flere lokale landingssider.",
  },
  {
    id: "cluster-price",
    siteId: visibilitySite.id,
    name: "Pris og kostnad",
    intent: "price_cost_comparison",
    commercialValue: 95,
    coverageScore: 61,
    keywordIds: ["kw-price"],
    winningPageType: "Prisguide med kort svar, drivere, eksempler og CTA",
    gap: "Prisguiden rangerer, men sender ikke nok trafikk videre til lokal konverteringsside.",
    recommendedNextStep: "Legg internlenke og kort svarblokk. Vurder prisseksjon på tjenestesider.",
  },
  {
    id: "cluster-trust",
    siteId: visibilitySite.id,
    name: "Trygghet og valg",
    intent: "trust_safety_doubt",
    commercialValue: 78,
    coverageScore: 45,
    keywordIds: ["kw-bokforing"],
    winningPageType: "Tjenesteside med case, prosess, ekspertprofil og anmeldelser",
    gap: "Siden forklarer tjenesten, men viser lite bevis på erfaring og metode.",
    recommendedNextStep: "Legg trust-modul og case før bredere innholdsproduksjon.",
  },
];

export const competitorObservations: CompetitorObservation[] = [
  {
    id: "comp-aider",
    siteId: visibilitySite.id,
    competitor: "Aider",
    domain: "aider.no",
    sharedKeywords: 4,
    strongerOn: ["Tydeligere tjenestesider", "Mer sosialt bevis", "Sterkere merkevaresignaler"],
    weakerOn: ["Mindre lokal Oslo-spissing", "Lite konkret prisforklaring"],
    contentPatterns: ["Prosessforklaring", "Kundecaser", "Tjenesteundersider"],
    recommendedResponse: "Ikke kopier bredden. Slå dem på lokal relevans, prisforklaring og konkret neste steg.",
    updatedAt: "2026-06-16",
  },
  {
    id: "comp-tripletex",
    siteId: visibilitySite.id,
    competitor: "Tripletex",
    domain: "tripletex.no",
    sharedKeywords: 2,
    strongerOn: ["Prisrelaterte guider", "Autoritet på regnskapssystem", "Featured snippet-format"],
    weakerOn: ["Ikke lokal tjenesteleverandør", "Mindre personlig rådgivning"],
    contentPatterns: ["Korte definisjoner", "Tabeller", "FAQ"],
    recommendedResponse: "Bruk enkel prisforklaring, men knytt den til lokal rådgivning og fast kontaktperson.",
    updatedAt: "2026-06-16",
  },
  {
    id: "comp-azets",
    siteId: visibilitySite.id,
    competitor: "Azets",
    domain: "azets.no",
    sharedKeywords: 3,
    strongerOn: ["Autoritet", "Bred tjenestedekning", "Lokale og nasjonale signaler"],
    weakerOn: ["Kan oppleves stort og lite konkret for små bedrifter"],
    contentPatterns: ["Bransjesider", "Rådgivningsartikler", "Skjema-CTA"],
    recommendedResponse: "Posisjoner Regnskapspartner som enklere og mer direkte for små bedrifter i Oslo.",
    updatedAt: "2026-06-16",
  },
];

export const paidAdsCampaigns: PaidAdsCampaign[] = [
  {
    id: "paid-google-oslo",
    siteId: visibilitySite.id,
    channel: "google_ads",
    name: "Search - Regnskapsfører Oslo",
    status: "limited",
    objective: "leads",
    spend: 14800,
    previousSpend: 9800,
    impressions: 18400,
    clicks: 612,
    ctr: 0.033,
    cpc: 24.18,
    conversions: 14,
    conversionRate: 0.023,
    costPerConversion: 1057,
    landingPage: "/regnskapsforer-oslo",
    qualityScore: 5,
    updatedAt: "2026-06-16",
    nextAction: "Reduser budsjett midlertidig og fiks landingssiden før kampanjen skaleres videre.",
  },
  {
    id: "paid-google-price",
    siteId: visibilitySite.id,
    channel: "google_ads",
    name: "Search - Pris og kostnad",
    status: "enabled",
    objective: "leads",
    spend: 6200,
    previousSpend: 5900,
    impressions: 9100,
    clicks: 344,
    ctr: 0.038,
    cpc: 18.02,
    conversions: 11,
    conversionRate: 0.032,
    costPerConversion: 564,
    landingPage: "/hva-koster-regnskapsforer",
    qualityScore: 7,
    updatedAt: "2026-06-16",
    nextAction: "Test mer direkte CTA til lokal tjenesteside for søk med høy kjøpsintensjon.",
  },
  {
    id: "paid-meta-lead",
    siteId: visibilitySite.id,
    channel: "meta_ads",
    name: "Meta - Småbedrift lead magnet",
    status: "learning",
    objective: "leads",
    spend: 3900,
    previousSpend: 4200,
    impressions: 32400,
    clicks: 286,
    ctr: 0.009,
    cpc: 13.64,
    conversions: 6,
    conversionRate: 0.021,
    costPerConversion: 650,
    landingPage: "/produkter/regnskapspakke-start",
    updatedAt: "2026-06-16",
    nextAction: "Bytt kreativ mot tydeligere problem/løfte og koble landingssiden til produktbeskrivelsen.",
  },
];

export const paidAdsAlerts: PaidAdsAlert[] = [
  {
    id: "paid-alert-cpa-oslo",
    siteId: visibilitySite.id,
    campaignId: "paid-google-oslo",
    type: "cpa_increase",
    severity: "high",
    title: "CPA har økt kraftig",
    description: "Kostnad per lead er 1057 kr, opp fra rundt 700 kr i forrige periode.",
    recommendedAction: "Stram inn søkeord, legg til negative søk og forbedre prissvar på landingssiden.",
    createdAt: "2026-06-16",
  },
  {
    id: "paid-alert-landing-oslo",
    siteId: visibilitySite.id,
    campaignId: "paid-google-oslo",
    type: "landing_page_mismatch",
    severity: "high",
    title: "Annonse og landingsside matcher svakt",
    description: "Annonsene lover prisavklaring, men landingssiden har ikke tydelig prisseksjon i første skjermbilde.",
    recommendedAction: "Legg prissvar og tydelig lead-CTA på /regnskapsforer-oslo før budsjettet økes.",
    createdAt: "2026-06-16",
  },
  {
    id: "paid-alert-overlap-price",
    siteId: visibilitySite.id,
    campaignId: "paid-google-price",
    type: "organic_paid_overlap",
    severity: "medium",
    title: "Betalt og organisk konkurrerer om samme søk",
    description: "Prisguiden får både betalt trafikk og organisk synlighet for flere av de samme søkene.",
    recommendedAction: "Skill søk med kjøpsintensjon fra informasjonsintensjon og mål samlet CPA/lead.",
    createdAt: "2026-06-16",
  },
];

export const paidLandingPageObservations: PaidLandingPageObservation[] = [
  {
    id: "paid-lp-oslo",
    siteId: visibilitySite.id,
    url: "/regnskapsforer-oslo",
    paidSpend: 14800,
    paidConversions: 14,
    organicClicks: 42,
    pageScore: 58,
    issue: "Høy annonsekostnad sendes til en side som mangler tydelig prissvar og lokal FAQ.",
    recommendedAction: "Oppdater landingssiden før videre skalering av betalt søk.",
  },
  {
    id: "paid-lp-price",
    siteId: visibilitySite.id,
    url: "/hva-koster-regnskapsforer",
    paidSpend: 6200,
    paidConversions: 11,
    organicClicks: 68,
    pageScore: 76,
    issue: "Siden fungerer godt som informasjonsinngang, men bør sende flere kjøpsklare brukere videre.",
    recommendedAction: "Legg sterkere internlenke og CTA til lokal tjenesteside.",
  },
  {
    id: "paid-lp-product-start",
    siteId: visibilitySite.id,
    url: "/produkter/regnskapspakke-start",
    paidSpend: 3900,
    paidConversions: 6,
    organicClicks: 9,
    pageScore: 44,
    issue: "Betalt Meta-trafikk lander på en produktside med svak beskrivelse.",
    recommendedAction: "Forbedre produktbeskrivelsen før ny kreativ test kjøres.",
  },
];

export const externalAuthorityRecommendations: ExternalAuthorityRecommendation[] = [
  {
    id: "authority-external-mentions",
    siteId: visibilitySite.id,
    title: "Bli nevnt på relevante eksterne sider",
    type: "external_mentions",
    priority: 86,
    relatedUrl: "/om-oss",
    issue:
      "Bedriften har svake eksterne signaler sammenlignet med større konkurrenter, spesielt på lokale og bransjerelevante sider.",
    recommendation:
      "Jobb målrettet med ekte omtaler fra lokale aktører, samarbeidspartnere, kundeprofiler og bransjeoversikter.",
    whyItMatters:
      "Søkemotorer og AI-systemer bruker ikke bare innholdet på egen nettside. Eksterne omtaler hjelper dem å forstå hvem bedriften er, hvor den holder til og hvorfor den er troverdig.",
    suggestedTargets: [
      "Lokal næringsforening i Oslo",
      "Kundecase hos samarbeidspartner",
      "Bransjeoversikt for regnskapsførere",
      "Sponsor-/partnerprofil der relasjonen allerede finnes",
    ],
    measurement: "Mål nye referring domains, brand mentions, referral-trafikk og synlighet for merkevaresøk.",
    riskNote: "Ikke kjøp lenker eller legg bedriften i irrelevante kataloger. Dette skal være ekte omtaler.",
  },
  {
    id: "authority-outbound-citations",
    siteId: visibilitySite.id,
    title: "Lenk ut til troverdige kilder der det hjelper brukeren",
    type: "outbound_citations",
    priority: 78,
    relatedUrl: "/hva-koster-regnskapsforer",
    issue:
      "Prisguiden forklarer regnskap, men viser ikke tydelig hvilke offentlige regler eller frister som ligger bak rådene.",
    recommendation:
      "Legg inn få, relevante utgående lenker til autoritative kilder når siden omtaler regler, frister eller dokumentasjon.",
    whyItMatters:
      "Gode eksterne kildehenvisninger gjør innholdet mer etterprøvbart og nyttig. Det kan styrke tillit uten å sende brukeren bort fra kjøpsreisen.",
    suggestedTargets: ["Skatteetaten", "Altinn", "Brønnøysundregistrene", "Regnskap Norge"],
    measurement: "Mål engagement, scroll, CTR til CTA og om AI-/AEO-tester oppfatter siden som mer dokumentert.",
    riskNote: "Lenk kun der kilden faktisk støtter påstanden. Ikke fyll siden med tilfeldige eksterne lenker.",
  },
  {
    id: "authority-expert-source",
    siteId: visibilitySite.id,
    title: "Bruk ekspertprofil som kilde i egne og eksterne saker",
    type: "expert_source",
    priority: 72,
    relatedUrl: "/om-oss",
    issue:
      "Siden viser lite om hvem som faktisk står bak rådene. Det gjør det vanskeligere å bygge ekspertise over tid.",
    recommendation:
      "Lag en kort ekspertprofil for fagansvarlig og bruk personen som kilde i guider, caser og eksterne omtaler.",
    whyItMatters:
      "Person- og ekspertise-signaler gjør innholdet mer troverdig for brukere, søk og svarmotorer.",
    suggestedTargets: ["Om oss-side", "Prisguide", "Kundecase", "Lokale næringsartikler"],
    measurement: "Mål om ekspertprofilen får interne lenker, eksterne omtaler og brukes i AI-svar/kildesammendrag.",
    riskNote: "Ikke overdriv ekspertise. Bruk konkrete erfaringer, roller og fagområder.",
  },
];

export const aiVisibilityTests: AiVisibilityTest[] = [
  {
    id: "ai-price-oslo",
    prompt: "Hva koster regnskapsfører i Oslo?",
    testedAt: "2026-06-16",
    provider: "OpenAI",
    mentionedBrand: false,
    mentionedCompetitors: ["Conta", "Tripletex"],
    citedSources: ["regnskapspartner-demo.no/hva-koster-regnskapsforer"],
    summary:
      "Merkevaren nevnes ikke i svaret, men prisguiden er en relevant kilde for generelle prisforklaringer.",
    gaps: ["Mangler lokal prisseksjon", "Lite tydelig tjenesteområde for Oslo"],
    recommendedActions: ["Legg prissvar på Oslo-siden", "Koble prisguiden til lokal tjenesteside"],
  },
  {
    id: "ai-small-business",
    prompt: "Hvem tilbyr regnskap for små bedrifter i Oslo?",
    testedAt: "2026-06-16",
    provider: "OpenAI",
    mentionedBrand: true,
    mentionedCompetitors: ["Azets", "Aider"],
    citedSources: ["regnskapspartner-demo.no/regnskapsforer-oslo"],
    summary: "Merkevaren nevnes, men svaret mangler tydelige bevis på erfaring og kundeprofil.",
    gaps: ["Mangler caser", "Mangler ekspertprofil"],
    recommendedActions: ["Legg trust-modul på tjenestesider", "Oppdater Om oss med erfaring og metode"],
  },
];

export const integrations: Integration[] = [
  {
    id: "int-gsc",
    siteId: visibilitySite.id,
    type: "google_search_console",
    name: "Google Search Console",
    status: "mocked",
    description:
      "Henter søk, sider, klikk, visninger, CTR og gjennomsnittlig posisjon. Brukes til å finne tiltak med organisk potensial.",
    lastSyncedAt: "2026-06-16",
    nextStep: "Logg inn med Google-konto som har tilgang til riktig Search Console-property.",
  },
  {
    id: "int-ga4",
    siteId: visibilitySite.id,
    type: "google_analytics",
    name: "Google Analytics 4",
    status: "mocked",
    description:
      "Henter sessions, engagement og konverteringer per landingsside. Brukes til å prioritere tiltak etter faktisk verdi.",
    lastSyncedAt: "2026-06-16",
    nextStep: "Velg GA4-konto, property og web stream. Kontroller at viktige konverteringer er satt opp.",
  },
  {
    id: "int-google-ads",
    siteId: visibilitySite.id,
    type: "google_ads",
    name: "Google Ads",
    status: "mocked",
    description:
      "Henter kampanjer, spend, klikk, CPC, konverteringer, CPA, quality score og søketerms for å finne sløsing og skaleringsmuligheter.",
    lastSyncedAt: "2026-06-16",
    nextStep: "Koble Google Ads-konto med lesetilgang og velg hvilke konverteringer som teller som reell verdi.",
  },
  {
    id: "int-meta-ads",
    siteId: visibilitySite.id,
    type: "meta_ads",
    name: "Meta Ads",
    status: "coming_soon",
    description:
      "Planlagt støtte for kampanjer, creatives, spend, leads og landingssider slik at betalt sosialt kan måles mot innholdskvalitet.",
    nextStep: "Aktiver når første kunde skal koble Meta Business Manager.",
  },
  {
    id: "int-wp",
    siteId: visibilitySite.id,
    type: "wordpress",
    name: "WordPress",
    status: "needs_setup",
    description: "Klar for test connection og utkastflyt. Publisering skjer ikke automatisk.",
    nextStep: "Legg inn site URL og application password.",
  },
  {
    id: "int-shopify",
    siteId: visibilitySite.id,
    type: "shopify",
    name: "Shopify",
    status: "coming_soon",
    description: "Grunnstruktur for produkter, samlinger, sider og blogginnlegg.",
    nextStep: "Aktiver når første Shopify-kunde er klar.",
  },
  {
    id: "int-gbp",
    siteId: visibilitySite.id,
    type: "google_business_profile",
    name: "Google Business Profile",
    status: "coming_soon",
    description: "UI-plass og datamodell er klar for lokal synlighet.",
    nextStep: "Koble på GBP API i senere fase.",
  },
];

export const weeklyReport: WeeklyReport = {
  id: "report-2026-w25",
  organizationId: visibilityOrganization.id,
  siteId: visibilitySite.id,
  weekStart: "2026-06-15",
  weekEnd: "2026-06-21",
  summary:
    "Denne uken bør Regnskapspartner prioritere eksisterende sider med synlighet fremfor å lage nye sider. De raskeste gevinstene ligger i CTR, prisforklaring og internlenking.",
  focusActions: [
    "Endre title/meta på /regnskapsforer-oslo",
    "Legg til prisseksjon på /regnskapsforer-oslo",
    "Legg internlenke fra /hva-koster-regnskapsforer til /regnskapsforer-oslo",
  ],
  authorityAdvice: [
    "Bli nevnt på 2-3 relevante eksterne sider: lokal næringsforening, samarbeidspartner eller kundecase.",
    "Legg få, presise utgående lenker til Skatteetaten, Altinn eller Brønnøysundregistrene der siden forklarer regler og frister.",
    "Lag en kort ekspertprofil som kan brukes både på egne sider og i eksterne omtaler.",
  ],
  quickWin: "Title/meta på Oslo-siden kan gjøres på 15 minutter og måles etter 28 dager.",
  biggestRisk:
    "Å lage mange lokale sider nå kan gi tynt og repetitivt innhold før hovedsidene er tydelige nok.",
  status: "needs_review",
  html:
    "<h1>Ukens organiske synlighetstiltak</h1><p>Hvis du bare gjør tre ting denne uken, start med CTR, prissvar og internlenke.</p>",
};

export const aiUsageLogs: AiUsageLog[] = [
  {
    id: "usage-1",
    model: "gpt-4.1-mini",
    taskType: "recommendation_enrichment",
    inputTokens: 1840,
    outputTokens: 620,
    costEstimate: 0.018,
    createdAt: "2026-06-16",
  },
  {
    id: "usage-2",
    model: "gpt-4.1-mini",
    taskType: "quality_gate",
    inputTokens: 980,
    outputTokens: 340,
    costEstimate: 0.009,
    createdAt: "2026-06-16",
  },
];

export const dashboardMetrics = {
  visibilityScore: 74,
  weeklyChange: 8,
  technicalIssues: 1,
};

export const visibilityTrend = [
  { week: "U20", score: 58 },
  { week: "U21", score: 60 },
  { week: "U22", score: 63 },
  { week: "U23", score: 66 },
  { week: "U24", score: 66 },
  { week: "U25", score: 74 },
];

export const pricingPlans = [
  {
    name: "Starter",
    price: "490-990 kr/mnd",
    description: "For små bedrifter som vil ha få, tydelige tiltak hver uke.",
    highlighted: false,
    features: [
      "1 nettsted",
      "Search Console og GA4",
      "Ukentlig rapport",
      "Maks 3 tiltak per uke",
      "SEO + enkel AEO",
      "E-postrapport og dashboard",
    ],
  },
  {
    name: "Growth",
    price: "1 490-2 990 kr/mnd",
    description: "Hovedpakken for bedrifter som vil jobbe aktivt med organisk synlighet.",
    highlighted: true,
    features: [
      "Alt i Starter",
      "Maks 10 tiltak per uke",
      "WordPress- eller Shopify-tilkobling",
      "Google Ads-overvåkning",
      "AEO-score per side",
      "Lokal synlighetsanalyse",
      "Før/etter-måling og rapport",
    ],
  },
  {
    name: "Pro / Agency",
    price: "4 990-9 990 kr/mnd",
    description: "For byråer og mer aktive bedrifter med flere nettsteder.",
    highlighted: false,
    features: [
      "Flere nettsteder",
      "White-label rapporter",
      "Konkurrentanalyse",
      "AI-synlighetsmonitor",
      "Automatiske CMS-utkast",
      "Eksport/API og flere brukere",
    ],
  },
  {
    name: "Done-for-you",
    price: "5 000-25 000 kr/mnd",
    description: "For kunder som vil at tiltakene utføres etter godkjenning.",
    highlighted: false,
    features: [
      "Alt i Growth/Pro",
      "Vi utfører tiltakene",
      "Månedlig strategimøte",
      "Publisering i CMS etter godkjenning",
      "Innholdsforbedringer og lokal SEO",
      "Rapportering",
    ],
  },
];
